export const ADD_USER = 'ADD_USER';
export const LOGIN = 'LOGIN';
export const SUBMIT_WORKORDER = 'SUBMIT_WORKORDER'
export const ADD_WORK_ORDER = 'ADD_WORK_ORDER'
export const QUERY_WORKORDER = 'QUERY_WORKORDER'
export const QUERY_RENT_PAYMENTS = 'QUERY_RENT_PAYMENTS'
export const UPDATE_WORKORDER = 'UPDATE_WORKORDER'